select * from customer limit 20

--Total revenue generated by male and female
select gender, sum(purchase_amount) as revenue from customer
group by gender

--who used discounts but still paid more
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer)

--top 5 best rating products
select item_purchased, Round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by "Average Product Rating" desc
limit 5

--compare average purchase amount between standard and express shipping
select shipping_type, Round(avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more 
select subscription_status, count (customer_id) as total_customers, Round(avg(purchase_amount),2) as average_spend, Round(sum(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend desc

--top 5 products with highest purchase price with discounts applied
select item_purchased, Round(100*sum(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

--segment customers into new, returning, and loyal
with customer_type as(
select customer_id, previous_purchases, 
CASE 
WHEN previous_purchases = 1 THEN 'New'
WHEN previous_purchases Between 2 and 10 then 'Returning'
ELSE 'loyal'
END AS customer_segment
from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--top 3 most purchased product within each category
with item_counts as(
select category, item_purchased, count(customer_id) as total_orders, 
Row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

-- are repeat customers more likely to be a subscribers

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases >=5
group by subscription_status


--revenue contribution of each agegroup

select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc


